### ISSUE TITLE
WIP: Update Android Example.

### ISSUE THREAD

**Issue by joshuapinter** [gitim/react-native-sortable-list#15]
I'm adding this "work in progress" issue here to keep tabs on getting the Android example updated to the excellent-looking iOS example. I feel bad for poor, old Android. 

This is their current state: 
![before](https://cloud.githubusercontent.com/assets/180819/23593370/51513a04-01cb-11e7-8c56-f696857599f9.gif)

My goal with this is to make the Android version look as good as the iOS version.

The actual work will be done over on my fork at https://github.com/joshuapinter/react-native-sortable-list.

# TODO:

- [x] Update UI to use card-like interface for each kitty. 
- [x] Use elevation for non-activated rows.
- [x] Update kitty picture in first row - not working.
- [x] Add increased elevation to active row whilst dragging. 
- [x] Add similar screencast for Android to README.
- [ ] Add option to pass "draggable anchor element" to row (to allow for easy scrolling). 
- [x] Or, see if you can fix the scrolling issue on Android.

**Comment by joshuapinter** [comment]
## Status Update: 

![after](https://cloud.githubusercontent.com/assets/180819/23595465/491ded0a-01df-11e7-9f33-6a614241857c.gif)

**Comment by joshuapinter** [comment]
Issue PR #18 to update the Android example app with the styling seen in the above GIF. I think it looks beautiful.

Also issued:
* PR #16 to update the picture of the first kitten.
* PR #17 to update Gradle build tools, SDK build tools and React Native dependency.

Still need to figure out a way to scroll in Android without dragging. But I think that can be solved one of two ways: 

1. Allow a draggable area of the row instead of using the entire row. 

2. Doing some work on the long press stuff happening on the android side and see if we can avoid kicking off the drag event until the user does a long press. Otherwise, let the OS UI handle the scrolling event as normal.

**Comment by joshuapinter** [comment]
Fixed scrolling in Android in #20 . Essentially, the PanResponder was hijacking the gesture from the OS so scrolling was nearly impossible, especially with the UI changes that extend the rows fully to each side.

Now we don't block the OS from handling the scroll event unless the user issues a long press (200ms) on one of the rows, at which point scrolling is disabled and you can drag the row around as you'd like. 

Not an easy fix to find but it ended up just being a few lines to solve, thanks to this obscure post over here: https://github.com/facebook/react-native/issues/8488

That's why the internet and GitHub is a beautiful thing, sharing knowledge and making it relatively accessible is the greatest thing humankind has done. 🙏

**Comment by gitim** [comment]
@joshuapinter big thanks for your help with fixing android 👍. It looks than we can publish a new version to npm, do we?

**Comment by joshuapinter** [comment]
I would say so. And if I can suggest, I would say this warrants a 1.0.0 npm version release. Everything is very stable. 

The only thing I would like added is having a handle to start the drag instead of the whole row. Any thoughts on that?

Thanks.

**Comment by gitim** [comment]
just noticed this in android while autoscrolling:
![-07-2017 00-44-37](https://cloud.githubusercontent.com/assets/3778452/23631434/828adf4e-02cf-11e7-820d-c8ea2a944aa4.gif)

maybe this is issue with emulator, but I am not sure.

**Comment by gitim** [comment]
> The only thing I would like added is having a handle to start the drag instead of the whole row. Any thoughts on that?

I think it is possible to add something like touchableAreaPaddingLeft, touchableAreaPaddingRight,... and use them in [_isTouchInsideElement](https://github.com/gitim/react-native-sortable-list/blob/master/src/Row.js#L206) check

**Comment by joshuapinter** [comment]
Yeah, I see that too on my emulator, but it only happens if you release without making any movements at the end of an autoscroll. If you just move it a little after you get to the end of the list via autoscroll it correctly places it at the end. 

I'd say minor issue but maybe add a new issue to catalogue it.

**Comment by srameshr** [comment]
@joshuapinter Was this resolved? On android it just snaps back to original position.

**Comment by joshuapinter** [comment]
@srameshr Not by me but it wasn't a big issue in real world usage. We've got this running in production and it's working great.

**Comment by alz10** [comment]
@joshuapinter hi joshua, how did you manage to prevent the scrolling effect in `ScrollView` or `FlatList` when dragging the component?

[react-native-drag-drop-and-swap](https://github.com/ranvir-gorai/react-native-drag-drop-and-swap) I'm using this library unfortunately, it has a bug when the draggable component is inside the ScrollView or FlatList
